name: i_remember
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  image_picker: ^0.4.10
  sqflite: ^0.13.0
  path_provider:
  rxdart:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
